module.exports = {
    "host": "https://api.qingcloud.com/iaas/",
    "version": 1,
    "signature_version": 1,
    "actions": {
        "DescribeInstances": {
            "required": ["zone"],
            "optional": ["instances.n", "image_id.n", "instance_type.n", "status.n", "search_word", "verbose", "offset", "limit"]
        },
        "RunInstances": {
            "required": ["image_id", "zone"],
            "optional": ["instance_type", "count", "cpu", "memory", "instance_name", "login_mode", "login_keypair", "login_passwd", "vxnets.n", "security_group","volumes.n","need_newsid","need_userdata","userdata_type","userdata_value","userdata_path","userdata_file"]
        },
        "TerminateInstances": {"required": ["instances.n", "zone"], "optional": []},
        "StartInstances": {"required": ["instances.n", "zone"], "optional": []},
        "StopInstances": {"required": ["instances.n", "zone"], "optional": ["force"]},
        "RestartInstances": {"required": ["instances.n", "zone"], "optional": []},
        "ResetInstances": {"required": ["instances.n", "zone"], "optional": ["login_mode","login_keypair","login_passwd","need_newsid"]},
        "ResizeInstances": {"required": ["instances.n"], "optional": ["instance_type", "cpu", "memory", "zone"]},
        "ModifyInstanceAttributes": {"required": ["instance", "zone"], "optional": ["instance_name", "description"]},

        "DescribeVolumes": {"required": ["zone"], "optional": ["volumes.n", "volume_type", "status.n", "search_word", "verbose", "offset", "limit"]},
        "CreateVolumes": {"required": ["size", "zone"], "optional": ["volume_name", "volume_type", "count"]},
        "DeleteVolumes": {"required": ["volumes.n", "zone"], "optional": []},
        "AttachVolumes": {"required": ["volumes.n", "instance", "zone"], "optional": []},
        "DetachVolumes": {"required": ["volumes.n", "instance", "zone"], "optional": []},
        "ResizeVolumes": {"required": ["volumes.n", "size", "zone"], "optional": []},
        "ModifyVolumeAttributes": {"required": ["volume", "zone"], "optional": ["volume_name", "description"]},

        "DescribeVxnets": {"required": ["zone"], "optional": ["vxnets.n", "vxnet_type", "search_word", "verbose", "offset", "limit"]},
        "CreateVxnets": {"required": ["zone", "vxnet_type"], "optional": ["vxnet_name", "count"]},
        "DeleteVxnets": {"required": ["zone", "vxnets.n"], "optional": []},
        "JoinVxnet": {"required": ["zone", "vxnet", "instances.n"], "optional": []},
        "LeaveVxnet": {"required": ["zone", "vxnet", "instances.n"], "optional": []},
        "ModifyVxnetAttributes": {"required": ["zone", "vxnet"], "optional": ["vxnet_name", "description"]},
        "DescribeVxnetInstances": {"required": ["zone", "vxnet"], "optional": ["instances.n", "instance_type", "status", "image", "offset", "limit"]},

        "DescribeRouters": {"required": ["zone"], "optional": ["routers.n", "status.n", "search_word", "verbose", "offset", "limit"]},
        "CreateRouters": {"required": ["zone"], "optional": ["router_name", "count", "router_type", "security_group"]},
        "DeleteRouters": {"required": ["zone", "routers.n"], "optional": []},
        "UpdateRouters": {"required": ["zone", "routers.n"], "optional": []},
        "PowerOffRouters": {"required": ["zone", "routers.n"], "optional": []},
        "PowerOnRouters": {"required": ["zone", "routers.n"], "optional": []},
        "JoinRouter": {"required": ["zone", "router", "vxnet", "ip_network"], "optional": ["features"]},
        "LeaveRouter": {"required": ["zone", "vxnets.n", "router"], "optional": []},
        "ModifyRouterAttributes": {"required": ["zone", "router"], "optional": ["eip", "security_group", "router_name", "description"]},
        "DescribeRouterStatics": {"required": ["zone"], "optional": ["router_statics.n", "router", "static_type", "verbose", "offset", "limit"]},
        "AddRouterStatics": {"required": ["zone", "router"], "optional": ["statics.n.router_static_name","statics.n.static_type", "statics.n.val1", "statics.n.val2", "statics.n.val3", "statics.n.val4","statics.n.val5"]},
        "ModifyRouterStaticAttributes":{"required":["zone", "router_static"],"optional": ["router_static_name","val1","val2","val3","val4","val5","val6"]},
        "DeleteRouterStatics": {"required": ["zone", "router_statics.n"], "optional": []},
        "DescribeRouterVxnets": {"required": ["zone"], "optional": ["router", "vxnet", "verbose", "offset", "limit"]},
        "AddRouterStaticEntries": {"required": ["zone", "router_static","entries.n.val1","entries.n.val2"], "optional": []},
        "DeleteRouterStaticEntries": {"required": ["zone", "router_static_entries.n"], "optional": []},
        "ModifyRouterStaticEntryAttributes": {"required": ["zone", "router_static_entry"], "optional": ["router_static_entry_name","val1","val2"]},
        "DescribeRouterStaticEntries": {"required": ["zone"], "optional": ["router_static","offset","limit"]},

        "DescribeEips": {"required": ["zone"], "optional": ["eips.n", "instance_id", "status.n", "search_word", "offset", "limit"]},
        "AllocateEips": {"required": ["zone", "bandwidth"], "optional": ["billing_mode","eip_name", "count", "need_icp"]},
        "ReleaseEips": {"required": ["zone", "eips.n"], "optional": []},
        "AssociateEip": {"required": ["zone", "eip", "instance"], "optional": []},
        "DissociateEips": {"required": ["zone", "eips.n"], "optional": []},
        "ChangeEipsBandwidth": {"required": ["zone", "eips.n", "bandwidth"], "optional": []},
        "ChangeEipsBillingMode": {"required": ["zone", "eips.n", "billing_mode"], "optional": []},
        "ModifyEipAttributes": {"required": ["zone", "eip"], "optional": ["eip_name", "description"]},

        "DescribeSecurityGroups": {"required": ["zone"], "optional": ["security_groups.n", "search_word", "verbose", "offset", "limit"]},
        "CreateSecurityGroup": {"required": ["zone"], "optional": ["security_group_name"]},
        "DeleteSecurityGroups": {"required": ["zone", "security_groups.n"], "optional": []},
        "ApplySecurityGroup": {"required": ["zone", "security_group"], "optional": ["instances.n"]},
        "ModifySecurityGroupAttributes": {"required": ["zone", "security_group"], "optional": ["security_group_name", "description"]},
        "DescribeSecurityGroupRules": {"required": ["zone"], "optional": ["security_group", "security_group_rules.n", "direction", "offset", "limit"]},
        "AddSecurityGroupRules": {"required": ["zone", "security_group", "rules.n.protocol", "rules.n.priority"], "optional": ["rules.n.security_group_rule_name", "rules.n.action", "rules.n.direction", "rules.n.val1", "rules.n.val2", "rules.n.val3"]},
        "DeleteSecurityGroupRules": {"required": ["zone", "security_group_rules.n"], "optional": []},
        "ModifySecurityGroupRuleAttributes": {"required": ["zone", "security_group_rule"], "optional": ["security_group_rule_name","priority","rule_action","direction","protocol","val1","val2","val3"]},

        "DescribeKeyPairs": {"required": ["zone"], "optional": ["keypairs.n", "instance_id", "encrypt_method", "search_word", "verbose", "offset", "limit"]},
        "CreateKeyPair": {"required": ["zone"], "optional": ["keypair_name", "mode", "encrypt_method", "public_key"]},
        "DeleteKeyPairs": {"required": ["zone", "keypairs.n"], "optional": []},
        "AttachKeyPairs": {"required": ["zone", "keypairs.n", "instances.n"], "optional": []},
        "DetachKeyPairs": {"required": ["zone", "instances.n", "keypairs.n"], "optional": []},
        "ModifyKeyPairAttributes": {"required": ["zone", "keypair"], "optional": ["keypair_name", "description"]},

        "DescribeImages": {
          "required": ["zone"],
          "optional": ["images.n", "processor_type", "os_family", "visibility", "provider", "status.n", "search_word", "verbose", "offset", "limit"]
        },
        "CaptureInstance": {"required": ["instance", "zone"], "optional": ["image_name"]},
        "DeleteImages": {"required": ["images.n", "zone"], "optional": []},
        "ModifyImageAttributes": {"required": ["image", "zone"], "optional": ["image_name", "description"]},
        "GrantImageToUsers": {"required": ["images", "zone","users.n"], "optional": []},
        "RevokeImageFromUsers": {"required": ["images", "zone","users.n"], "optional": []},

        "CreateLoadBalancer": {"required": ["zone"], "optional": ["eips.n","vxnet","private_ip","loadbalancer_type","loadbalancer_name","security_group"]},
        "DescribeLoadBalancers": {"required": ["zone"], "optional": ["loadbalancers.n","status.n","search_word","verbose","offset","limit"]},
        "DeleteLoadBalancers": {"required": ["loadbalancers.n", "zone"], "optional": []},
        "ModifyLoadBalancerAttributes": {"required": ["loadbalancer", "zone"], "optional": ["loadbalancer_name","security_group","description","private_ip"]},
        "StartLoadBalancers": {"required": ["loadbalancers.n", "zone"], "optional": []},
        "StopLoadBalancers": {"required": ["loadbalancers.n","zone"], "optional": []},
        "UpdateLoadBalancers": {"required": ["loadbalancers.n","zone"], "optional": []},
        "ResizeLoadBalancers": {"required": ["loadbalancers.n","loadbalancer_type","zone"], "optional": []},
        "AssociateEipsToLoadBalancer": {"required": ["eips.n","loadbalancer", "zone"], "optional": []},
        "DissociateEipsFromLoadBalancer": {"required": ["eips.n","loadbalancer", "zone"], "optional": []},
        "AddLoadBalancerListeners": {
            "required": ["loadbalancer","listeners.n.listener_port","listeners.n.listener_protocol","listeners.n.backend_protocol","zone"],
            "optional": ["listeners.n.loadbalancer_listener_name","listeners.n.balance_mode","listeners.n.session_sticky","listeners.n.forwardfor","listeners.n.healthy_check_method","listeners.n.healthy_check_option","listeners.n.listener_option"]
        },
        "DescribeLoadBalancerListeners": {"required": ["zone"], "optional": ["loadbalancer_listeners.n","loadbalancer","verbose","offset","limit"]},
        "DeleteLoadBalancerListeners": {"required": ["loadbalancer_listeners.n", "zone"], "optional": []},
        "ModifyLoadBalancerListenerAttributes": {
            "required": ["loadbalancer_listener", "zone"],
            "optional": ["loadbalancer_listener_name","balance_mode","session_sticky","forwardfor","healthy_check_method","healthy_check_option","listeners.n.listener_option"]
        },
        "AddLoadBalancerBackends": {"required": ["loadbalancer_listener","backends.n.resource_id","backends.n.port","backends.n.weight","zone"], "optional": ["backends.n.loadbalancer_backend_name"]},
        "DescribeLoadBalancerBackends": {"required": ["zone"], "optional": ["loadbalancer_backends.n","loadbalancer_listener","loadbalancer","verbose","offset","limit"]},
        "DeleteLoadBalancerBackends": {"required": ["loadbalancer_backends.n", "zone"], "optional": []},
        "CreateLoadBalancerPolicy": {"required": ["zone"], "optional": ["operator","loadbalancer_policy_name"]},
        "DescribeLoadBalancerPolicies": {"required": ["zone"], "optional": ["loadbalancer_policies.n","lloadbalancer_policy_name","verbose","offset","limit"]},
        "ModifyLoadBalancerPolicyAttributes": {"required": ["loadbalancer_policy", "zone"], "optional": ["loadbalancer_policy_name","operator"]},
        "ApplyLoadBalancerPolicy": {"required": ["loadbalancer_policy", "zone"], "optional": []},
        "DeleteLoadBalancerPolicies": {"required": ["loadbalancer_policies.n", "zone"], "optional": []},
        "AddLoadBalancerPolicyRules": {"required": ["loadbalancer_policy","rules.n.rule_type","rules.n.val", "zone"], "optional": ["rules.n.loadbalancer_policy_rule_name"]},
        "DescribeLoadBalancerPolicyRules": {"required": ["zone"], "optional": ["loadbalancer_policy_rules.n","loadbalancer_policy","offset","limit"]},
        "ModifyLoadBalancerPolicyRuleAttributes": {"required": ["loadbalancer_policy_rule", "zone"], "optional": ["loadbalancer_policy_rule_name","val"]},
        "DeleteLoadBalancerPolicyRules": {"required": ["loadbalancer_policy_rules.n", "zone"], "optional": []},

        "GetMonitor":{"required":["resource","meters.n","step","start_time","end_time","zone"],"optional": []},
        "GetLoadBalancerMonitor":{"required":["resource","meters.n","step","start_time","end_time","zone"],"optional": []},
        "GetRDBMonitor":{"required":["resource","meters.n","step","start_time","end_time","zone"],"optional": []},
        "GetCacheMonitor":{"required":["resource","meters.n","step","start_time","end_time","zone"],"optional": []},
        "GetMongoMonitor":{"required":["resource","meters.n","step","start_time","end_time","zone"],"optional": []},

        "DescribeSnapshots":{"required":["zone"],"optional": ["snapshots.n","resource_id","snapshot_type","status.n","search_word","verbose","offset","limit"]},
        "CreateSnapshots":{"required":["resources.n","zone"],"optional": ["snapshot_name","is_full"]},
        "DeleteSnapshots":{"required":["snapshots.n","zone"],"optional": []},
        "ApplySnapshots":{"required":["snapshots.n","zone"],"optional": []},
        "ModifySnapshotAttributes":{"required":["snapshot","zone"],"optional": ["snapshot_name","description"]},
        "CaptureInstanceFromSnapshot":{"required":["snapshot","zone"],"optional": ["image_name"]},
        "CreateVolumeFromSnapshot":{"required":["snapshot","zone"],"optional": ["volume_name"]},

        "UploadUserDataAttachment":{"required":["attachment_content","zone"],"optional": ["attachment_name"]},

        "DescribeJobs":{"required":["zone"],"optional": ["jobs.n","status.n","job_action","verbose","offset","limit"]},

        "DescribeZones":{"required":[],"optional": ["zones.n","status.n"]},

        "CreateRDB":{"required":["vxnet","rdb_username","rdb_password","rdb_type","storage_size","zone"],"optional": ["rdb_engine","engine_version","rdb_name","description","auto_backup_time"]},
        "DescribeRDBs":{"required":["zone"],"optional": ["rdbs.n","status.n","rdb_name","verbose","offset","limit"]},
        "DeleteRDBs": {"required": ["rdbs.n", "zone"], "optional": []},
        "StartRDBs": {"required": ["rdbs.n", "zone"], "optional": []},
        "StopRDBs": {"required": ["rdbs.n", "zone"], "optional": []},
        "ResizeRDBs": {"required": ["rdbs.n", "zone"], "optional": ["rdb_type","storage_size"]},
        "RDBsLeaveVxnet": {"required": ["rdbs.n","vxnet","zone"], "optional": []},
        "RDBsJoinVxnet": {"required": ["rdbs.n","vxnet","zone"], "optional": []},
        "CreateRDBFromSnapshot": {"required": ["rdb_type","vxnet","zone"], "optional": ["rdb_name","description","auto_backup_time"]},
        "GetRDBInstanceFiles": {"required": ["rdb_instance","zone"], "optional": []},
        "CopyRDBInstanceFilesToFTP": {"required": ["rdb_instance","files.n","zone"], "optional": []},

        "DescribeCaches":{"required": ["zone"], "optional": ["caches.n","status.n","search_word","verbose","offset","limit"]},
        "CreateCache":{"required": ["vxnet","cache_size","cache_type","zone"], "optional": ["node_count","cache_name","cache_parameter_group","private_ips.n.cache_role","private_ips.n.private_ips"]},
        "StopCaches":{"required": ["caches.n","zone"], "optional": []},
        "StartCaches":{"required": ["caches.n","zone"], "optional": []},
        "RestartCaches":{"required": ["caches.n","zone"], "optional": []},
        "DeleteCaches":{"required": ["caches.n","zone"], "optional": []},
        "ResizeCaches":{"required": ["caches.n","cache_size","zone"], "optional": []},
        "UpdateCache":{"required": ["cache","zone"], "optional": ["private_ips.n.cache_node_id","private_ips.n.private_ip"]},
        "ChangeCacheVxnet":{"required": ["cache","vxnet","zone"], "optional": ["private_ips.n.cache_node_id","private_ips.n.private_ip"]},
        "ModifyCacheAttributes":{"required": ["cache","zone"], "optional": ["cache_name","description"]},
        "DescribeCacheNodes":{"required": ["zone"], "optional": ["cache","cache_nodes.n","status.n","search_word","verbose","offset","limit"]},
        "AddCacheNodes":{"required": ["cache","node_count","zone"], "optional": ["private_ips.n.cache_role","private_ips.n.private_ips"]},
        "DeleteCacheNodes":{"required": ["cache","cache_nodes.n","zone"], "optional": []},
        "RestartCacheNodes":{"required": ["cache","cache_nodes.n","zone"], "optional": []},
        "ModifyCacheNodeAttributes":{"required": ["cache_node","cache_node_name","zone"], "optional": []},
        "CreateCacheFromSnapshot":{"required": ["snapshot","vxnet","zone"], "optional": ["node_count","cache_name","cache_parameter_group","private_ips.n.cache_role","private_ips.n.private_ips"]},
        "DescribeCacheParameterGroups":{"required": ["zone"], "optional": ["cache_parameter_groups.n","cache_type","search_word","verbose","offset","limit"]},
        "CreateCacheParameterGroup":{"required": ["cache_type","zone"], "optional": ["cache_parameter_group_name"]},
        "ApplyCacheParameterGroup":{"required": ["cache_parameter_group","zone"], "optional": ["caches.n"]},
        "DeleteCacheParameterGroups":{"required": ["zone"], "optional": ["cache_parameter_groups.n"]},
        "ModifyCacheParameterGroupAttributes":{"required": ["cache_parameter_group","zone"], "optional": ["cache_parameter_group_name","description"]},
        "DescribeCacheParameters":{"required": ["cache_parameter_group","zone"], "optional": []},
        "UpdateCacheParameters":{"required": ["cache_parameter_group","parameters.n.cache_parameter_name","parameters.n.cache_parameter_value","zone"], "optional": []},
        "ResetCacheParameters":{"required": ["cache_parameter_group","zone"], "optional": ["cache_parameter_names.n"]},

        "DescribeMongoNodes":{"required": ["mongo","zone"], "optional": ["offset","limit"]},
        "DescribeMongoParameters":{"required": ["mongo","zone"], "optional": ["offset","limit"]},
        "ResizeMongos":{"required": ["mongos.n","zone"], "optional": ["mongo_type","storage_size"]},
        "CreateMongo":{"required": ["vxnet","zone"], "optional": ["mongo_version","mongo_type","storage_size","mongo_name","description","auto_backup_time","private_ips"]},
        "StopMongos":{"required": ["mongos.n","zone"], "optional": []},
        "StartMongos":{"required": ["mongos.n","zone"], "optional": []},
        "DescribeMongos":{"required": ["zone"], "optional": ["mongos.n","status.n","mongo_name","verbose","offset","limit"]},
        "DeleteMongos":{"required": ["mongos.n","zone"], "optional": []},
        "CreateMongoFromSnapshot":{"required": ["vxnet","mongo_type","zone"], "optional": ["mongo_name","description"]},
        "ChangeMongoVxnet":{"required": ["mongo","vxnet","zone"], "optional": ["private_ips"]},
        "AddMongoInstances":{"required": ["mongo","zone"], "optional": ["node_count","private_ips"]},
        "RemoveMongoInstances":{"required": ["mongo","mongo_instances","zone"], "optional": []},
        "ModifyMongoAttributes":{"required": ["mongo","zone"], "optional": ["mongo_name","description","auto_backup_time"]},
        "ModifyMongoInstances":{"required": ["mongo","zone"], "optional": ["private_ips"]}
    },
    "errors": [
        {"code": 1100, "client": true, "type": "消息格式错误", "tip": "当缺少必要参数，或者参数值格式不正确时，会返回该错误。此时可以查看相关文档确认每个参数的格式是否正确。"},
        {"code": 1200, "client": true, "type": "身份验证失败", "tip": "当用户提供了不存在的access_key_id参数，或者API请求的签名不正确时，会返回该错误。此时可以检查access_key_id和secret_access_key是否配置正确，或者参考我们的签名文档 签名方法 检查是否签名有误。"},
        {"code": 1300, "client": true, "type": "消息已过期", "tip": "当用户提交的 time_stamp 参数时间过期时会返回该错误。关于 time_stamp ，可以参考 公共参数"},
        {"code": 1400, "client": true, "type": "访问被拒绝", "tip": "当用户试图访问不属于自己的资源，或者对于提交的操作没有权限，或者试图更改的资源处于不可更改的状态时等，会返回该错误。我们会在返回的错误信息里头提及错误原因。"},
        {"code": 2100, "client": true, "type": "找不到资源", "tip": "当用户试图访问不存在的资源时，会返回该错误。"},
        {"code": 2500, "client": true, "type": "超过配额", "tip": "当用户试图创建的资源超过用户配额，或者短时间内的API访问请求超过配额限制，会返回该错误。您可以通过提交工单的方式来向我们申请提高配额，并说明你申请的理由。"},
        {"code": 5000, "client": false, "type": "内部错误", "tip": "当服务器执行请求过程中，遇到未知错误时，会返回该错误信息。遇到这种错误，请及时与我们联系。"},
        {"code": 5100, "client": false, "type": "服务器繁忙", "tip": "当服务器执行超时，或者服务器负载过高无法完成请求时，会返回该错误信息。遇到这种错误，请稍后再尝试，或者及时与我们联系。"},
        {"code": 5200, "client": false, "type": "资源不足", "tip": "当我们后台计算资源不足以满足用户的创建需求时，会返回该错误信息。遇到这种错误，请及时与我们联系。"},
        {"code": 5300, "client": false, "type": "服务更新中", "tip": "当我们的后台服务正在更新时，可能会返回该错误信息。遇到这种错误，请稍后再尝试，或者及时与我们联系。"}
    ]
}